version: "3.8"

services:
  db:
    container_name: postgres-db
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  web:
    container_name: cve-search-web
    build: 
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static/:/code/static/
      - ./media/:/code/media/
    links:
      - db
    env_file: .env
    depends_on:
      - db

  selenium:
    container_name: selenium-grid
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

networks:
  default:
    external:
      name: nginx-proxy